- src/plugins/env.ts
- src/routes/coingeckoProxy/index.ts
Use Coingecko's api key in the proxy requests
> feat: add coingecko api key

- package-lock.json
- package.json
- src/plugins/env.ts
- src/routes/coingeckoProxy/index.ts
Different attempt at coingecko proxy.
Relying solely on Vercel CDN for caching, without the server side caching introduced on https://github.com/cowprotocol/bff/pull/10
> feat: coingecko proxy without server side caching

- apps/bff/src/app/plugins/env.ts
- apps/bff/src/app/routes/proxies/coingecko/index.ts
- apps/bff/src/app/routes/proxies/tokens/index.ts
- apps/bff/src/app/routes/proxy/index.ts
- apps/twap/src/app/plugins/orderbook.ts
- apps/twap/src/app/utils/getApiBaseUrl.ts
- apps/twap/src/app/utils/getConditionalOrderId.ts
- package.json
- yarn.lock
> chore: merge main to develop

- apps/api/project.json
- apps/notification-producer/project.json
- apps/telegram/project.json
- apps/twap/project.json
- package.json
This PR just use our convention `start` instead of `serve` to run a service
Modifies the API, telegram, and producer so now you can run them with `start`
> Improve project config

- apps/notification-producer/src/main.ts
- apps/notification-producer/src/postToQueueTest.ts
- apps/telegram/src/main.ts
- libs/cms-api/src/index.ts
- libs/notifications/src/index.ts
This PR fixes a bunch of issues related to the notifications publisher and consumer
Publisher
- Fixed main loop, it was not working as expected
- Keep connection alive, handle closing of the queue
- Handle error posting the message (tries to re-attempt later when the connection is established). Before it was loosing the message. Still needs improvement, but requires an API change
- Generaral refactors and logging improvements
- Recover from errors
Consumer
- Fixed main loop, it was not working as expected
- Keep connection alive, handle closing of the queue
- Generaral refactors and logging improvements
- Recover from errors
- start queue with docker
- start producer with NX
- start consumer with NX
- Add a notification in the CMS
You can try to see how if we kill the queue, both services …
> Improve pub subs

- .env.example
- .github/workflows/docker.yml
- apps/api/src/app/routes/about/index.ts
This PR is an attempt to allow us to see in any service what is the version we are running and what commit.
I added one additional step in the build that writes a text file with the git commit hash. 
This file is then read by the `/about` endpoint, which if present it will expose this hash
> Expose commit hash and version in the about service

- .github/workflows/docker.yml
This PR adds the auto-deployment to staging. 
Every time a PR is merged with `main`, it will notify the auto-deployer so it can restart the services that depend on the newly generated images.
Because of the image pull policy, the restart will pull and use the new images
@ahhda, I think we need to set this secrets, but I'm unsure about the value. 
~secrets.AUTODEPLOY_TAG~ (edit: not needed)
secrets.AUTODEPLOY_URL
secrets.AUTODEPLOY_TOKEN
I guess the URL is what i see in 1password in "K8S autodeploy auth", the token I assume is the "password". What is the TAG?
> Auto-deploy to staging when merging in main branch

- apps/api/src/app/plugins/swagger.ts
- apps/api/src/app/routes/about.ts
Hide some routes in swagger
Run locally, check the new swagger docs, you should only see the `/about` endpoint
Check the old one, you should see a lot of stuff you don't want to see:
https://bff.barn.cow.fi/docs/static/index.html
> Hide some routes in swagger

- .github/workflows/docker.yml
- apps/api/src/app/plugins/env.ts
- apps/api/src/app/routes/proxies/coingecko/index.ts
- apps/api/src/main.ts
This PR has a lot of misc changes oriented to test the correct caching of the API.
This PR will improve our debuggability, and will make it easier to test in staging some PR.
I will use it to make sure even if there was not CDN, our AWS won't ask our API twice for a resource that is cacheable. 
First of all, we want to test this in our infra (AWS), so it would be easier if we can test already before needing to merge this PR.
For this reason, I made the build of packages be triggered on every commit. This will publish new packages on every change. 
We can use this packages in staging k8s, making it easier to test
You can see now a new tag: `pr-36`: https://github.com/cowprotocol/bff/pkgs/container/bff%2Fapi
This allow us to run it even before this PR is merged:
Adds a new environment …
> Misc on improving debugability and making sure CACHEs work

- apps/api/src/app/connections/redis.ts
- apps/api/src/app/plugins/caching.ts
- apps/api/src/app/plugins/redis.ts
This PR tries to fix the issue that makes the app crash if REDIS is not setup.
If the envs don't provide the redis host, it will be understood we don't use redis, so it will not using it in the plugins.
> Don't crash if redis is not up

- apps/api/src/app/routes/proxies/coingecko/index.ts
The cache override had a bug, and was never overriding the cache.
It was always returning 30s cache, which comes from coingecko.
I used now `COINGECKO_CACHING_TIME=3600` and has effect:
> Fix overriding cache headers

- .env.example
- apps/api/src/app/plugins/bffAuth.ts
Adds a basic auth layer. Is not bullet proof, but it helps to prevent unauthorized access.
It will:
- Protect some specific paths. For now: `['/proxies']`
- It will verify check the origin is what it expects. Should be in the known origins that can be set by `env`: AUTHORIZED_DOMAINS
Request should go through no matter what. No 403 expected. Just test with different origins
Add to your env:
```
AUTHORIZED_ORIGINS=cow.fi
```
Make sure it works when origin is our localhost:3000 app:
```bash
curl -i 'http://localhost:3010/proxies/tokens' \
-H 'content-type: application/json' \
-H 'Origin: http://localhost:3000' \
--data-raw $'{"query":"\\n  query SearchTokens($searchQuery: String\u0021) {\\n    searchTokens(searchQuery: $searchQuery) {\\n      id\\n      decimals\\n      name\\n …
```
> Add a simple authentication based on authorized domains

- apps/api/src/app/routes/proxy/index.ts
BFF is live, so we don't need anymore serveless functions from Vercel.
This PR deletes the legacy proxy
> Delete legacy proxy endpoint

- apps/api/src/app/plugins/bffCache.ts
- apps/api/src/app/routes/about.ts
- apps/api/src/app/routes/examples/hello.ts
- apps/api/src/main.ts
Make use of the logger in the API project. 
Its best to not use directly the console log, because we expect some specific format in the logs we parse (we use pino logger)
This PR removes some console.logs and replaces by the logger
> Use logger for the API project

- apps/api/src/app/app.ts
- apps/api/src/app/routes/chains/__chainId/markets/__sellToken-__buyToken/defaultSlippageTolerance.ts
- apps/api/src/app/schemas.ts
This PR makes a mock endpoint we can use to get the default slippage
This way, we can implement on a later PR our heuristic (using coingecko API, orderbook API, CMS, or whatever we see suitable)
The endpoint will validate the chain is an integer:
Also that is supported chain:
Same for the market, it will require they are Ethereum addresses.
This is a mock value that returns our current default, we can discuss the heuristic now and iterate on this. 
https://bff.barn.cow.fi/chains/1/markets/0x6b175474e89094c44da98b954eedeac495271d0f-0x2260fac5e5542a773aa44fbcfedf7c193bc2c599/defaultSlippageTolerance
> Expose default slippage

- apps/api/src/app/routes/chains/__chainId/markets/__sellToken-__buyToken/defaultSlippageTolerance.ts
- apps/api/src/app/routes/chains/__chainId/markets/__sellToken-__buyToken/slippageTolerance.ts
Small iteration on #45 to improve the swagger docs.
I changed my mind also regarding the parameters. I like more the base/quote notation for modeling markets
> feat: improve swagger docs for the slippage endpoint

- apps/api/src/app/routes/chains/__chainId/markets/__sellToken-__buyToken/slippageTolerance.ts
- libs/repositories/.eslintrc.json
- libs/repositories/README.md
- libs/repositories/jest.config.ts
- libs/repositories/project.json
- libs/repositories/src/UsdRepository.ts
- libs/repositories/tsconfig.json
- libs/repositories/tsconfig.lib.json
- libs/repositories/tsconfig.spec.json
- libs/services/.eslintrc.json
- libs/services/README.md
- libs/services/jest.config.ts
- libs/services/project.json
- libs/services/src/SlippageService/SlippageService.spec.ts
- libs/services/src/SlippageService/SlippageService.ts
- libs/services/src/index.ts
- libs/services/tsconfig.json
- libs/services/tsconfig.lib.json
- libs/services/tsconfig.spec.json
- tsconfig.base.json
- yarn.lock
This PR is the first of a series I'd like to add to BFF.
We will have a growing complexity in BFF and I thought about making a suggestion.
My general plan is to:
- Create 2 new libraries `services` (in this PR) and `repositories` (follow up)
- Our API will just delegate all work to a service, this way, the API layer remains lightweight and all business logic is moved to the service.
- The service might make use of one or more repositories to access the information 
- The repositories allows us to abstract how we access the data (separation on data access from the service logic)
- I would also like to work with Typescript interfaces for these 2 layers (to hide implementation details), and potentially have more than one implementation. This will help with unit testing for example, or …
> Add slippage service - suggest 3 layered architecture

- apps/api/src/app/inversify.config.ts
- apps/api/src/app/routes/chains/__chainId/markets/__baseTokenAddress-__quoteTokenAddress/slippageTolerance.ts
- apps/api/src/app/routes/chains/__chainId/tokens/__tokenAddress/usdPrice.ts
- libs/repositories/src/UsdRepository/UsdRepositoryRedis.ts
- libs/services/src/SlippageService/SlippageService.ts
- libs/services/src/UsdService/UsdService.ts
- libs/services/src/index.ts
This PR implements a very basic UsdService, which just delegates to the repository. Because the service logic is dumb I didn't do any unit tests (it feels overkill, the relevant tests for USD are in the repositories)
The repository is injected, so the service doesn't care about the specific implementation.
Exposes the service through a basic API
`/chains/1/tokens/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/usdPrice` 
#alfetopito I know you don't like. I'm happy to do a refactor to `/1/tokens/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/usdPrice` but we will need to then make it backward compatible with the slippage endpoint. I added chains to be more explicit (I think is not the purest API definition, if the ID there doesn't have context), but we can compromise that for simplicity's sake. …
> Implement and expose USD service

- apps/api/src/app/inversify.config.ts
- libs/services/src/SlippageService/SlippageService.ts
- libs/services/src/SlippageService/SlippageServiceMain.spec.ts
- libs/services/src/SlippageService/SlippageServiceMain.ts
- libs/services/src/SlippageService/SlippageServiceMock.ts
- libs/services/src/index.ts
The previous implementation couldn't get to production, because it would change the default slippage tolerance used in CoW Swap.
This PR provides a temporal implementation, so we can keep working iteratively in having this service ready
`curl http://localhost:3010/chains/1/markets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2-0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/slippageTolerance -v`
> Implement mock slippage for backwards compatibility

- apps/api/src/app/plugins/bffCache.ts
- package.json
Changes based off of https://github.com/cowprotocol/bff/releases/tag/v0.6.3 which is the current prod version.
Pointing to the new branch `v0.6`.
It fixes the issue with cached responses.
The requests are being cached, but the cached part is the stream, not the the actual payload.
Since the stream is consumed in the first reply, the subsequent tries in the cached version return nothing:
```
"err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (/Users/alfeto/work/cow/bff/node_modules/fastify/lib/reply.js:127:26)\n    at /Users/alfeto/work/cow/bff/node_modules/@fastify/reply-from/index.js:184:14\n    at /Users/alfeto/work/cow/bff/node_modules/@fastify/reply-from/index.js:277:9\n    at …
```
> chore: hotfix v0.6.4

- apps/api/src/app/plugins/bffCache.ts
Now that the caching was fixed on https://github.com/cowprotocol/bff/pull/67, the next issue was exposed.
Unfortunately I only noticed after it was already deployed to prod :(
Right now, the cache is the SAME for all requests.
That's because the cache key used in the request path: `req.routerPath` which is `/proxies/coingecko/*` for all requests.
Changed to `req.url` which does contain the full url path including the search params. E.g.: `/proxies/coingecko/simple/token_price/ethereum?contract_addresses=0x6B175474E89094C44Da98b954EedeAC495271d0F&vs_currencies=usd`
1. Start the server locally with `yarn start`
2. Query one address: `curl -X GET http://localhost:3000/proxies/coingecko/simple/token_price/ethereum?contract_addresses=0x6B175474E89094C44Da98b954EedeAC495271d0F&vs_currencies=usd` …
> fix: use url as cache key which contains query params

- apps/api/src/app/inversify.config.ts
- apps/api/src/app/routes/__chainId/tokens/__tokenAddress/usdPrice.ts
- libs/repositories/src/CacheRepository/CacheRepository.ts
- libs/repositories/src/CacheRepository/CacheRepositoryMemory.ts
- libs/repositories/src/CacheRepository/CacheRepositoryRedis.ts
- libs/repositories/src/UsdRepository/UsdRepositoryCache.spec.ts
- libs/repositories/src/UsdRepository/UsdRepositoryCache.ts
- libs/repositories/src/index.ts
- package.json
- yarn.lock
This PR puts together all the repositories I was making for USD :) 
Basically, the endpoint service was exposed in the previous PR https://github.com/cowprotocol/bff/pull/60
This PR will make use of
- `UsdRepositoryFallback`: Will try first coingecko, and fallback in COW using native prices
- coingecko
- will be using `UsdRepositoryRedis` for caching
- And `UsdRepositoryCoingecko` for the implementation
- similarly, cow native USD price will use
- will be using `UsdRepositoryRedis` for caching
- And `UsdRepositoryCow` for the implementation 
Additionally, the UsdRepositoryRedis has been refactor to... not be dependant on Redis. 
I did this just to make it easier to run the app with caching logic but not depend on having a redis running. I implement the most simple interface for a KeyValue …
> Create usd repo using composition of other repos + In-memory caching

- apps/api/src/app/inversify.config.ts
- libs/repositories/src/UsdRepository/UsdRepositoryCache.ts
This PR increases the caching time for values to 2min.
It also makes the specification of the caching time mandatory, and moves its const to the `inversify` configuration. 
To test, you can add some logs (you can apply this changes https://github.com/cowprotocol/bff/pull/71/commits/6aedf885ae3657bac8890dc6a12138dd3df7d833)
Then you can query the price of these tokens:
- curl -i  http://127.0.0.1:3010/1/tokens/0x6b175474e89094c44da98b954eedeac495271d0f/usdPrice
- curl -i  http://127.0.0.1:3010/1/tokens/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/usdPrice 
It might be handy to change the caching time to `10 seconds`  https://github.com/cowprotocol/bff/blob/increase-caching-time/apps/api/src/app/inversify.config.ts#L15
> Increase caching time

- apps/api/src/app/routes/__chainId/markets/__baseTokenAddress-__quoteTokenAddress/slippageTolerance.ts
- apps/api/src/app/routes/accounts/_account/notifications.ts
- apps/api/src/app/routes/accounts/_account/notifications/index.ts
- libs/cms-api/src/index.ts
This PR exposes the notifications API in BFF.
Right now the Nofications are coming from the CMS, but some notifications can be added to some other sources (like a database, etc), also the notifications can be enhanced with on-chain data, or post-processed, for this reason, I think is convenient to expose it through BFF.
This would also allow us to remove the dependency from CoW Swap to the CMS and reduce the permissions of reading the notifications from the public endpoint (now is a securitized request)
Run locally and execute:
`curl -i http://localhost:3010/accounts/0x79063d9173C09887d536924E2F6eADbaBAc099f5/notifications`
> feat: expose notifications api

- apps/api/src/app/routes/accounts/_account/notifications.ts
This PR just adds a 5min cache for the notifications.
For now, the notifications don't need to be very fast. Its meant to be used for announcements. So we can afford to cache it for a few minutes. This way, we release some requests from our CMS, which has a limit in the number of requests the let us do.
> Add cache for notifications

- apps/api/src/app/plugins/bffCache.ts
- apps/api/src/app/routes/about.ts
- libs/repositories/src/gen/cow/cow-api-types.ts
- libs/repositories/src/utils/cache.ts
Freaking finally!! 
Fixed the cache 500 error I was getting for the slippage. 
1. I implemented caching, made it work for the proxy (coingecko).
2. Then used it for caching JSON content responses from other endpoints. The medications made the caching to work for the JSON, but broke coingecko
3. Then Leandro noticed the error from Coingecko endpoint (we were caching a stream, not the content), and fixed it --> for coingecko, but broke it for our slippage endpoint
After this, I enter a dance of fixing it to one, breaking it to the other and so on. After a bit of struggling I think I manage to make it work in this PR
Run locally
It doesn't have cache, so it won't have cache headers in the response
`curl http://127.0.0.1:3010/1/tokens/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/usdPrice`
``` …
```
> Fix caching issues

- .env.example
- apps/api/src/main.ts
- package.json
- yarn.lock
Developing locally was a bit complicated witht he logs we have. Pino logger writes in JSON format, which makes it super hard to read:
Now it uses the following pretty logger for local:
It will check the value of `NODE_ENV` and only when it is production, it will use the default JSON format.
> Make logs pretty for development

- .env.example
- apps/api/src/app/plugins/env.ts
- apps/api/src/app/routes/accounts/_account/notifications.ts
- apps/api/src/app/routes/proxies/coingecko/index.ts
- apps/api/src/app/routes/proxies/tokens/index.ts
- apps/api/src/app/routes/twap/index.ts
- libs/cms-api/src/index.ts
- libs/repositories/src/gen/cow/cow-api-types.ts
This PR relaxes the requirements for env configurations
It makes all envs optional providing fair default. 
For the proxies, if you don't pass the right env they won't be created. It will give you a warning though. 
It runs with no env file, it will give you just some relevant warn messages:
> Relax env configurations

- apps/api/src/app/plugins/bffCache.ts
- libs/repositories/src/CacheRepository/CacheRepository.ts
- libs/repositories/src/CacheRepository/CacheRepositoryMemory.ts
- libs/repositories/src/CacheRepository/CacheRepositoryRedis.ts
This PR fixes the current issue with the keys in redis (the special characters are encoded)
See  these keys:
I noticed that our cache repository don't have this behaviour, and this come from the abstract-cache. I just ditch it. Our repository is equivalent. I had to implement the TTL method, since we didn't have a way to get the expiration of keys. 
With that, it works as expected.
Tested with `curl -i http://localhost:3010/proxies/coingecko/simple/token_price/ethereum/\?contract_addresses\=0x6B175474E89094C44Da98b954EedeAC495271d0F\&vs_currencies\=usd`
> Implement TTL and use our own repository to cache requests

- apps/api/src/app/plugins/env.ts
Match the pattern used on the rest of the code (check .env.example)
To test:
- Run the API locally and test with the request:
```
curl --request POST \
--url https://bff.barn.cow.fi/1/simulation/simulateBundle \
--header 'Content-Type: application/json' \
--header 'User-Agent: insomnia/10.0.0' \
--data '[
{
"from": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
"to": "0x0000000000000000000000000000000000000000",
"value": "1000000000000000000",
"input": "0x"
}
]'
```
> Fix simulation env var names on plugin

- libs/repositories/src/SimulationRepository/SimulationRepositoryTenderly.ts
This fix is due to a last change in the previous PR. To test, run the automatic tests with:
`nx test repositories --testFile=libs/repositories/src/SimulationRepository/SimulationrepositoryTenderly.test.ts`
> fix deep copy error on build balances diff

- apps/api/src/app/routes/__chainId/simulation/simulateBundle.ts
- libs/repositories/src/SimulationRepository/SimulationRepository.ts
- libs/repositories/src/SimulationRepository/SimulationRepositoryTenderly.ts
- libs/repositories/src/SimulationRepository/SimulationrepositoryTenderly.test.ts
Run the automatic tests with:
`nx test repositories --testFile=libs/repositories/src/SimulationRepository/SimulationrepositoryTenderly.test.ts`
By the way, as you can see the gas parameter is returned even in failed simulations, so maybe we don't need to make the hook app pass a `maxGasLimit` parameter.
> feat: add `gasUsed` data on tenderly simulation endpoint

- libs/repositories/src/SimulationRepository/SimulationRepository.ts
- libs/repositories/src/SimulationRepository/SimulationRepositoryTenderly.ts
- libs/repositories/src/SimulationRepository/tenderlyTypes.ts
This PR only changes the type to optional and returns the null gas used since the value will not be presented
> fix: change tenderly transaction type to optional on tenderly simulation

- apps/telegram/src/main.ts
This PR handles the error that's making crashlooping in prod. We just crash if the queue message has not the right format
Also, prints some useful info on which part throws an error
> fix: handle errors

- libs/repositories/src/gen/cow/cow-api-types.ts
- libs/repositories/src/index.ts
- libs/repositories/src/repos/UserBalanceRepository/UserBalanceRepository.ts
- libs/repositories/src/repos/UserBalanceRepository/UserBalanceRepositoryCache.ts
- libs/repositories/src/repos/UserBalanceRepository/UserBalanceRepositoryViem.ts
This is the first PR of a series of PR to include: Live Balance and Allowance tracking using SSE  (see #157)
The goal is to define a minimalistic interface to load the balances and allowances.
The PR includes 2 implementations:
* `UserBalanceRepositoryViem`: Basic implementation in viem. Uses `multicall` to fetch all balances and allowances for the tokens using a simple RPC node.
* `UserBalanceRepositoryCache`: Adds a caching layer. This will use in-memory cache by default, or REDIS if setup (like we have currently in production)
The PRs from this hackathon will document in #157 some TODOs I left behind. These should be straightforward to address later, but they were not the main focus during the hackathon.  
Specifically, this PR:  
- Skips loading `symbol`, `name`, and `decimals`. We …
> feat: add user balance repository

- apps/api/src/app/inversify.config.ts
- libs/services/src/BalanceTrackingService/BalanceTrackingService.ts
- libs/services/src/BalanceTrackingService/BalanceTrackingServiceMain.ts
- libs/services/src/index.ts
This is the third PR of a series of PR to include: Live Balance and Allowance tracking using SSE  (see #157)
The goal is to define a service that manages start/stop tracking logic, delegates to the repository, and pushes updates via SSE  
The PR includes:
* `BalanceTrackingService`: Simple interface of the service. Defines relevant types, like the payload for balance/allowance change events . Also exposes `startTrackingUser` and `stopTrackingUser` to start monitoring the balance/allowance and do some actions when the balance changes (`onBalanceChange`).
* `BalanceTrackingServiceMain`: Implementation of the interface. It depends on the SSE Service (see #158) that can be optional injected. It also makes use of the balance repository (see #156) to fetch the balances and allowances. If the …
> feat: add tracking service
